name: 'Hello World'
description: 'Greet someone'
inputs:
  input-value:  # id of input
    description: 'Who to greet'
    required: true
    default: 'You'
outputs:
  value1:
    description: "Random number"
    value: ${{ steps.random-num.outputs.value1 }}
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.input-value }}
      shell: bash
    - run: echo ${{github.action_path }}
      shell: bash
    - id: random-num
      run: echo "::set-output name=value1::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - shell: bash
      run: |
        echo "Parent env val: $B"
    - id: foo2
      name: Run nested sub action
      uses: ./.github/workflows/action2 # actions/hello-world-composite-action@v1 # https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
      with:
        input-value: 'Nested sub action input value'