name: Create reusable workflow

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      secret1:
        required: true
    outputs:
      out1:
        description: "Output 1"
        value: ${{ jobs.build.outputs.output1 }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step2.outputs.outputa }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ secrets.secret1 }}"
          echo "${{ inputs.image }}"
          echo "${{ env.B }}"
      - id: step2
        run: echo "::set-output name=outputa::output-a-value 1"